# Numpy

[NumPy](https://numpy.org/) это open-source модуль для python, который предоставляет общие математические и числовые операции.

NumPy - один из ключевых модулей в экосистеме Python, в том числе при решении задач машинного обучения и искусственного интеллекта.

NumPy является наследником Numeric и NumArray. Основан NumPy на библиотеке LAPAC, которая написана на Fortran. Когда-то numpy была частью SciPy. Да, это напоминает мыльную оперу. 

Мы подробно разбираем особенности библиотеки, так как на работе с ней основаны все остальные библиотеки, работающие с искусственным интеллектом.

Текст урока опирается на небольшой, но полезный [мануал](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf).

## Установка

Если вы используете Google Colab, то numpy уже установлен на виртуальном сервере и вы можете им пользоваться.

Если вы открыли собственный ноутбук, то можете воспользоваться командой установки, записанной через восклицательный знак


```
!comand
```
Так запущенная команда в среде ipy вызывает системную команду pip, которая сама установит данный модуль в вашу виртуальную среду. 

Обратите внимание, что каждый ноутбк имеет свой набор используемых библиотек и системных установок. 


In [ ]:
!pip install numpy

## Подключение

Для подключения модулей в Python используется команда `import` или её вариации. В случае с numpy есть традиционная и привычная всем команда импорта с использованием алиаса (as) np

Алиас - это встроенная команда интерпретатора для сокращения команд и их последовательностей.

In [ ]:
# классический вариант
import numpy

In [ ]:
# традиционный вариант 
import numpy as np

При таком импорте к любым командам из модуля numpy придётся дописывать название модуля

```
numpy.comand
np.comand
```
Есть другой вариант, в котором можно использовать только команду без указания модуля. Но так как в разных модулях могут быть одинаковые функции, использовать такой вариант не рекомендуется.


In [ ]:
from numpy import *

## Особые константы

Numpy реализует несколько особых значнений через контстанты. Например:

In [ ]:
np.NaN
# not a number - Не число

nan

In [ ]:
np.Inf
# infinity - бесконечность 

inf

## Массивы

Главная особенность и элемент, с которым необходимо работать, в numpy - это массивы. Создаются массивы разными способами, которые мы сейчас разберём. 

При этом всем элементы в array должны быть одного типа, что отличает его от классического списка (list) Python. 

In [ ]:
a = np.array([1, 2, 3, 4], float)
print('Array:', a)
print('Тип: ',type(a))
# обратное преобразование
print(a.tolist())

Array: [1. 2. 3. 4.]
Тип:  <class 'numpy.ndarray'>
[1.0, 2.0, 3.0, 4.0]


In [ ]:
# показыаем, что можно также работать с np.array, как и с обычным list
a = np.array([1, 2, 4, 4])

print('1: ', a[0])
print('2: ', a[1:3])
print('3: ', a[-1])
a[0] = 5
print('4: ', a[0])

1:  1
2:  [2 4]
3:  4
4:  5


### Многомерные массивы 

Большая ценность numpy в том, что можно работать и многомерными массивами. Например, любое изображение - как минимум двумерный массив. А при обучении нейронных сетей для работы с компьютерным зрением используются по сути четырёхмерные массивы.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
print(a)
print('1: ', a[0,0])
print('2: ', a[1,0])
print('3: ', a[0,1])

[[1 2 3]
 [4 5 6]]
1:  1
2:  4
3:  2


In [ ]:
# срезы (сленг - слайсы) с двмерным массивом
print('4: ', a[1,:])
print('5: ', a[:,2])
print('6: ', a[-1:, -2:])

4:  [4 5 6]
5:  [3 6]
6:  [[5 6]]


### Характеристики объектов numpy

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
len(a)

2

In [ ]:
# размеры
a.shape

(2, 3)

In [ ]:
# тип данных внутри
# напоминаем, массив numpy может хранить только один тип данных
a.dtype

dtype('int64')

### Изменение размеров массива

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.reshape(3,2)

In [ ]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# с помощью этой команды можно вытянуть массив в одномерную "строку"
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Создание по-разному заполненных массивов

In [ ]:
# аналог range для массивов
print(np.arange(5))
print(np.arange(1, 6, 2))

[0 1 2 3 4]
[1 3 5]


In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# k - номер диагонали, заполненный единицами
np.eye(5,4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Перебор элементов массива

In [ ]:
a = np.array([1, 4, 5], int)

In [ ]:
# простой перебор для одномерного случая
for x in a:
   print(x)

1
4
5


In [ ]:
# простой перебор для многомерного случая срабаотает плохо, он перебирает по первой размерности
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
   print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# перебор правильным способом
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    print(a[x, y])

1.0
2.0
3.0
4.0
5.0
6.0


## Операции над массивами

### Математические операции над массивами

С массивами можно применять стандартные математические операции. Они будут работать так, как будето происходит поэлементая работа одной и той же операции. Для матричных операций есть специальные команды.

**Стандартные математические операции применимы только к массивам одинаковых размеров.**

In [ ]:
a = np.arange(1, 7, 1, dtype=int)
b = np.arange(6, 9, 1, dtype=int)
print('a: ', a)
print('b: ', b)

a:  [1 2 3 4 5 6]
b:  [6 7 8]


In [ ]:
a[3:] + b

array([10, 12, 14])

In [ ]:
a[3:] - b

array([-2, -2, -2])

In [ ]:
a[3:] * b

array([24, 35, 48])

In [ ]:
b / a

array([6.        , 3.5       , 2.66666667])

In [ ]:
a % b

array([1, 2, 3])

In [ ]:
b**a

array([  6,  49, 512])

In [ ]:
a // b

array([0, 0, 0])

Кроме того, поэлементно могут быть применены другие математические операции

In [ ]:
# корень
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
a = np.array([1.1, 1.5, 1.9], float)

In [ ]:
# округление вниз
np.floor(a)

array([1., 1., 1.])

In [ ]:
# округление вврех
np.ceil(a)

array([2., 2., 2.])

In [ ]:
# округление по правилам математики
np.rint(a)

array([1., 2., 2.])

### Простые операции над массивами

#### Одномерные массивы

In [ ]:
a = np.arange(1, 6, 1)
print(a)
print('Сумма: ', a.sum())
print('Перемножение: ', a.prod())

[1 2 3 4 5]
Сумма:  15
Перемножение:  120


In [ ]:
# среднее (математическое ожидание)
a.mean()

3.0

In [ ]:
# дисперсия (смещенная - это будет важно в дальнейшем)
a.var()

2.0

In [ ]:
# стандартное отклонение (несмещенное - это тоже будет важно в дальнейшем)
a.std()

1.4142135623730951

In [ ]:
a.min()

1

In [ ]:
a.argmin()

0

In [ ]:
# clip позволяет "отрезать" значения сверху и снизу
a = np.array([6, 2, 5, -1, 0, 6, 2, 5, 4], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0., 5., 2., 5., 4.])

In [ ]:
np.unique(a)

array([-1.,  0.,  2.,  4.,  5.,  6.])

#### Многомерные массивы
Для работы с многомерными массивами можно использовать параметр `axis`.

In [ ]:
a = np.array([[5, 2], [4, 1], [3, -1]])
print(a)
print(a.mean(axis=0))
print(a.mean(axis=1))
a.mean()

[[ 5  2]
 [ 4  1]
 [ 3 -1]]
[4.         0.66666667]
[3.5 2.5 1. ]


2.3333333333333335

### Логические операции над массивами

In [ ]:
a = np.array([1, 3, 0])
b = np.array([0, 3, 2])

print(a > b, type(a>b))

[ True False False] <class 'numpy.ndarray'>


In [ ]:
c = a > 2
c

array([False,  True, False])

In [ ]:
# проверяем, что хотя бы один элемент истинен
print(any(c))
# проверяем, что все элементы истинны
print(all(c))

True
False


Если вы хотите провести сравнение логическим И или логическим ИЛИ, то необходимо воспользоваться специальнымыми методами:


```
np.logical_and(_, _)
np.logical_or(_, _)
np.logical_not(_)
```



In [ ]:
(a < 3) * (a > 0)

array([[False,  True],
       [False,  True],
       [False, False]])

In [ ]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

С помощью `np.where` можно создать массив на основании условий. 
Синтаксис:


```
where(boolarray, truearray, falsearray)
```



In [ ]:
a = np.array([1, 3, 0])
a

array([1, 3, 0])

In [ ]:
np.where(a != 0, 1 / a, a)

<ipython-input-37-02e1e0c5bd2e>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a != 0, 1 / a, a)


array([1.        , 0.33333333, 0.        ])

Можно проверять элементы массива на наличие NaN и бесконечностей.

In [ ]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [ ]:
np.isnan(a)

array([False,  True, False])

In [ ]:
np.isfinite(a)

array([ True, False, False])

### Выбор элементов массива по условию

Очень важной особенностью массивов является то, что элементы в них можно брать на основании других массивов. Это особенно полезно при реализации свёрточных нейронных сетей.

In [ ]:
# это результат применения логической операции к многомерному массиву
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [ ]:
# а это результат фильтрации элементов
# обратите внимание, получился одномерный массив, содержащий только элементы, удовлетворяющие условию 
a[a >= 6]

array([6., 9.])

In [ ]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

Обратите внимание, что если передать целочисленные значения, в качестве условий, то результат будет другой. Будут выбраные соответствующие элементы. 

In [ ]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2], int)
a[b]

array([2., 2., 4., 8., 6.])

In [ ]:
# Для выбора значений из многомерных массивов необходимо передать массивы, которые определяют индексы по каждому из направлений. Они должны быть, естественно, целочисленными.
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

## Векторная и матричная математика с использованием numpy

Векторная математика в numpy - это главная причина того, что numpy стал ключевым модулем Python среди всех представленных модулей. Векторные вычисления позволяют значительно ускорить обработку численной информации. 

Часто сравнивая Python c С++/C говорят том, что первый гораздо менее производителен. Но с учётом современных модулей верно следующее утверждение: хорошо написанная программа на Python будет производительнее, чем средняя программа на C/C++, хорошую программу на C/C++ написать крайне сложно. 

В дополнении к арифметически операциям мы рассмотрим некоторые векторные операции. Глубокое погружение в их суть требует значительных знаний математики, которые мы будем получать по мере необходимости. 

### Скалярное произведение

Для двух векторов a и b одинаковой длины скалярное произведение считается по следующей формуле:

$ a*b = \sum_{i=0}^{len(a)}  a_i*b_i $

In [ ]:
# скалярное произвдение векторов, также операция свёртки в свёрточных нейронных сетях 

a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

### Произведение матриц

Произведение матриц - это особая математическая операция, которая не эквивалентна произведени соответствующих элементов матриц. О матричном произведении целесообразно говорить в рамках соответствующих разделов математики. Тем не менее, используя numpy легко получить матричное произведение.

In [ ]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
d = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]], float)

In [ ]:
np.dot(b, a)

array([ 6., 11.])

In [ ]:
np.dot(a, b)

array([ 3., 13.])

In [ ]:
a@b

array([ 3., 13.])

In [ ]:
# следите за размерностью, иначе ничего не получится
np.dot(b, d)

ValueError: ignored

### Определитель матриц

Многие математические операции, связанные с линейной алгеброй реализованы в модуле linalg внутри numpy. Мы не будем углулбляться в различные функциия модуля, рассмотрим для примера определитель. 

In [ ]:
np.linalg.det(a)

-2.0

# Дополнительный материал для желающих

[Нескучный туториал по numpy](https://habr.com/ru/post/469355/)

# Задания

In [3]:
!pip install numpy
import numpy as np

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```
Количество строк кода идеального решения: 2  
Кроме print()

In [4]:
N = 10
arr = np.ones((N, N))
arr[1:-1, 1:-1] = np.zeros((N - 2, N - 2))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1   
Кроме print()

In [5]:
N = 5
arr = sum([i * np.eye(N, N, k=i) for i in range(N)]) # not correct

# DeepSeek
arr = np.diag([1, 2, 3, 4], k=1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

**Задача 3.**

Дан массив, поменять знак у элементов, значения которых между 3 и 8.

In [6]:
arr = np.arange(10)
mask = np.logical_and(arr > 3, arr < 8)
arr[mask] = arr[mask] * -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

**Задача 4.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.zeros((len(arr), 4))
new_arr[:, 0] = arr
new_arr = new_arr.flatten()
new_arr

# DeepSeek
arr = np.array([1, 2, 3, 4, 5])
n = len(arr)
new_length = n + (n - 1) * 3  # Новая длина: 5 + 4*3 = 17
new_arr = np.zeros(new_length, dtype=arr.dtype)
indices = np.arange(0, new_length, 4)  # Позиции для исходных элементов: [0, 4, 8, 12, 16]
new_arr[indices] = arr

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

**Задача 5.**

Дана матрица MxN. Поменять 2 любые строки в матрице.

In [15]:
M, N = 3, 4
random_matrix = np.random.rand(M, N)
print(random_matrix)
random_matrix[1], random_matrix[2] = random_matrix[2].copy(), random_matrix[1].copy()
print(random_matrix)

#DeepSeek
M, N = 3, 4
random_matrix = np.random.rand(M, N)
print("Original matrix:")
print(random_matrix)

# Swap rows 1 and 2 using advanced indexing
random_matrix[[1, 2]] = random_matrix[[2, 1]]

print("\nMatrix after swapping rows 1 and 2:")
print(random_matrix)

[[0.33756548 0.8416234  0.65900179 0.96336925]
 [0.89636262 0.37089322 0.81960679 0.0229875 ]
 [0.66032474 0.10697565 0.74792793 0.06331826]]
[[0.33756548 0.8416234  0.65900179 0.96336925]
 [0.66032474 0.10697565 0.74792793 0.06331826]
 [0.89636262 0.37089322 0.81960679 0.0229875 ]]
Original matrix:
[[0.85019311 0.80008117 0.1371704  0.43974491]
 [0.61261345 0.02608564 0.83301689 0.9754058 ]
 [0.78917185 0.21257405 0.52810401 0.48798882]]

Matrix after swapping rows 1 and 2:
[[0.85019311 0.80008117 0.1371704  0.43974491]
 [0.78917185 0.21257405 0.52810401 0.48798882]
 [0.61261345 0.02608564 0.83301689 0.9754058 ]]


**Задача 6.**

Дан одномерный массив. Найти наиболее частое значение в массиве.

In [40]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
unique_elements, counts = np.unique(x, return_counts=True)
unique_elements[counts.argmax()]

np.int64(0)

**Задача 7.** 

Дан массив 16x16, посчитать сумму по блокам 4x4.

In [ ]:
N = 16
step = 4
random_matrix = np.random.rand(N, N)
new_matrix = np.zeros((N // step, N // step))
for i in range(0, N, step):
    for j in range(0, N, step):
        new_matrix[i // 4, j // 4] = np.sum(random_matrix[i:i + step, j:j + step])

new_matrix

# ChatGPT
import numpy as np

N = 16
step = 4
random_matrix = np.random.rand(N, N)

# reshape into (num_blocks_row, block_size, num_blocks_col, block_size)
blocks = random_matrix.reshape(N//step, step, N//step, step)

new_matrix = blocks.sum(axis=(1, 3))


array([[8.75750153, 7.08210443, 7.69186197, 7.70639097],
       [9.64301185, 9.42072868, 6.04096486, 7.36495293],
       [8.74431859, 8.10967049, 9.41108254, 7.19893363],
       [8.11668531, 7.15012953, 8.66409661, 7.64984523]])

**Задача 8.**

Дана матрица. Найти n наибольших значений в массиве. n вводится с клавиатуры.

In [20]:
N = 16
n = 5
random_matrix = np.random.rand(N, N)
random_vector = random_matrix.flatten()
random_vector.sort()
print(random_vector[-n:])

# Chat GPT
top_n = np.partition(random_vector, -n)[-n:]
print(top_n)

[0.98160043 0.98195562 0.99090575 0.99741675 0.99748943]
[0.98160043 0.98195562 0.99090575 0.99741675 0.99748943]


**Задача 9.**

Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3]).

In [59]:
matrix = np.array([
    [1, 2, 3],
    [2, 2, 3],
    [4, 5, 6]
])


matrix[(np.sum(matrix, axis=1) % 3) != 0]

array([[2, 2, 3]])

**Задача 10.**

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0


In [ ]:
N = 16
random_matrix = (np.random.rand(N, N) - 0.5) * 10
mask_greater = random_matrix > 0
mask_less = random_matrix < 0
result = np.ceil(random_matrix, where=mask_greater)
result = np.floor(result, where=mask_less)

array([[ 0.00000000e+000,  0.00000000e+000,  4.35495879e-315,
         4.35495879e-315,  5.84135394e-317, -3.00000000e+000,
         5.81078511e-317,  5.81459535e-317,  5.81078511e-317,
         5.81078511e-317,  6.13754470e-310,  1.00000000e+000,
         5.81606173e-317,  6.13754468e-310,  6.13754468e-310,
         2.00000000e+000],
       [-3.00000000e+000,  6.13756868e-310,  0.00000000e+000,
         6.13756868e-310,  6.13754470e-310, -3.00000000e+000,
         5.81570601e-317,  6.13754470e-310,  6.13754478e-310,
         5.81556371e-317, -4.00000000e+000,  5.84135394e-317,
         5.81565857e-317,  0.00000000e+000,  5.84135394e-317,
         5.84135394e-317],
       [-4.00000000e+000,  5.84135394e-317,  3.00000000e+000,
         5.84135394e-317,  5.84135394e-317,  5.81568229e-317,
         6.13756868e-310,  6.13754470e-310, -4.00000000e+000,
         5.81558743e-317, -4.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  3.00000000e+000,  0.00000000e+000,
         3.00000

In [26]:
#Chat gpt

import numpy as np

N = 16
random_matrix = (np.random.rand(N, N) - 0.5) * 10

Z = np.where(
    random_matrix > 0, np.ceil(random_matrix),
    np.where(random_matrix < 0, np.floor(random_matrix), 0)
)

print(Z)

[[-4.  2. -2.  3.  2. -1.  4.  2. -1.  3. -3. -3. -1. -2.  3.  2.]
 [ 4.  4.  5. -3. -1.  3.  5. -5. -3.  3. -4. -1.  4.  3.  4. -4.]
 [-1.  1.  5. -4. -4.  4.  3. -4. -4. -5. -4.  2.  5.  2.  1.  3.]
 [-1. -2.  3. -5.  5.  5.  2. -3.  2. -1. -3.  5.  5.  5. -1. -2.]
 [-4. -3.  1.  2.  1.  4.  2.  5.  4. -4.  2. -1. -5. -1. -4. -4.]
 [-5.  3. -4. -3. -1.  4.  1.  5.  4. -3.  3. -1. -5. -1. -5.  5.]
 [-3. -1. -2.  1. -2.  3.  4.  2.  2.  4. -1.  5. -4. -1. -2. -2.]
 [ 3.  3.  5. -4. -4. -1.  1. -5.  5. -2.  5. -5. -3. -5. -5.  4.]
 [-4. -4.  2.  5. -5. -3.  4.  2. -1.  4. -4.  4. -2.  4.  4.  1.]
 [-5.  2. -4.  5. -4.  1.  5. -5.  2.  5. -4.  4.  5.  4.  1. -5.]
 [-1. -4. -2. -4. -5.  3.  2. -2.  3. -5. -2.  2. -3. -4.  4.  5.]
 [-1.  1.  1.  3.  2. -5.  3. -1.  4.  1. -4.  2.  5. -4. -4.  1.]
 [-3.  2.  2. -4. -5. -2. -1. -3.  4. -5. -1.  5.  5. -1.  2.  4.]
 [ 1. -1. -3. -1. -2.  3. -1. -4. -4. -4. -4. -5. -2.  5. -1.  5.]
 [ 3.  5. -4.  3. -1. -4. -3. -2. -4.  3.  5. -3. -3.  5.  4. 

**Задача 11.**

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

In [1]:
# Chat GPT
import numpy as np

# Пример данных
A = np.array([1, 3, 5, 7, 9, 3, 1])
B = np.array([2, 3, 5, 7, 11, 3])

# Пересечение (отсортированное и без повторов)
Z = np.intersect1d(A, B)

print(Z)

[3 5 7]


**Задача 12.**

Дан вектр. Найти максимальный элемент в векторе среди элементов, перед которыми стоит нулевой. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.where(x[i])

**Задача 13.**

Дана матрица 5х3. Посчитать длинну каждого вектора в матрице (строка) и найти самый длинный ветор и вывести его координаты и длинну.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [33]:
M, N = 5, 3
random_matrix = np.random.rand(M, N) * 5
print(random_matrix)
len_vector = np.sqrt((random_matrix ** 2).sum(axis=1))
print(len_vector.argmax(), random_matrix[len_vector.argmax()])

# DeepSeek
# Создаем матрицу 5x3 со случайными значениями от 0 до 5
matrix = np.random.uniform(0, 5, size=(5, 3))

# Вычисляем длины векторов
lengths = np.linalg.norm(matrix, axis=1)

# Находим индекс самого длинного вектора
max_index = np.argmax(lengths)

# Извлекаем координаты самого длинного вектора и его длину
longest_vector = matrix[max_index]
longest_length = lengths[max_index]

# Выводим результаты
print("Матрица векторов:")
print("     x       y       z")
print(matrix)
print("\nДлины векторов:", lengths)
print(f"\nСамый длинный вектор (индекс {max_index}):")
print(f"x = {longest_vector[0]:.4f}, y = {longest_vector[1]:.4f}, z = {longest_vector[2]:.4f}")
print(f"Длина = {longest_length:.4f}")

[[1.74420078 2.72586272 1.33115471]
 [3.65868709 2.12942273 1.15205636]
 [3.11493206 0.72001153 2.32188692]
 [1.52644619 2.07153646 1.50772651]
 [0.7460379  0.98411508 4.18378114]]
1 [3.65868709 2.12942273 1.15205636]
Матрица векторов:
     x       y       z
[[0.92479867 2.20815728 3.94427991]
 [3.14280051 1.12144921 0.91329279]
 [2.3928991  0.53637991 3.1777923 ]
 [4.25552349 2.16376756 0.12541073]
 [3.08694366 4.98142545 4.87935621]]

Длины векторов: [4.61395223 3.45961661 4.01397974 4.77567776 7.62574178]

Самый длинный вектор (индекс 4):
x = 3.0869, y = 4.9814, z = 4.8794
Длина = 7.6257
